backend = "xrender";
vsync = false;
shadow = true;
shadow-radius = 16;
shadow-opacity = 0.18;
corner-radius = 16;
blur-method = "dual_kawase";
blur-strength = 3;
blur-background = true;
blur-background-frame = true;
inactive-opacity = 0.96;
active-opacity = 1.0;
frame-opacity = 0.88;
rounded-corners-exclude = [ "class_g = 'Plank'", "class_g = 'Xfce4-panel'" ];
opacity-rule = [
  "92:class_g = 'xfce4-terminal'",
  "88:class_g = 'Thunar'",
  "88:class_g = 'Plank'"
];
