backend = "xrender";
vsync = true;
shadow = true;
shadow-radius = 18;
shadow-offset-x = 0;
shadow-offset-y = 10;
shadow-opacity = 0.16;
corner-radius = 16;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

blur-background = true;
blur-method = "kernel";
blur-size = 7;
blur-deviation = 5.0;
blur-background-exclude = [
  "window_type = 'desktop'",
  "window_type = 'dock'",
  "class_g = 'VirtualBox Machine'"
];

opacity-rule = [
  "96:class_g = 'Thunar'",
  "96:class_g = 'Xfce4-terminal'",
  "96:class_g = 'Mousepad'",
  "94:class_g = 'light-locker'"
];

wintypes:
{
  dock = { shadow = false; };
  desktop = { shadow = false; };
};
